# Generated by Django 5.2.1 on 2025-06-08 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=100)),
                ('cover_url', models.URLField(help_text='Link gambar cover')),
                ('deskripsi', models.TextField()),
                ('pdf_url', models.URLField(blank=True, help_text='Opsional: Link PDF untuk diunduh', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Halaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.PositiveIntegerField()),
                ('gambar_url', models.URLField(help_text='Link gambar halaman')),
                ('pdf_url', models.URLField(blank=True, help_text='Opsional: Link PDF untuk diunduh', null=True)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halaman', to='halaman.buku')),
            ],
            options={
                'ordering': ['nomor'],
            },
        ),
    ]
