# Generated by Django 5.2.1 on 2025-06-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('cover_url', models.URLField(blank=True)),
                ('gdrive_embed_url', models.URLField(help_text='URL embed dari Google Drive')),
                ('gdrive_download_url', models.URLField(help_text='Link langsung untuk download PDF')),
            ],
        ),
    ]
